Add mapping for curve type and base field type
NilFoundation/zkllvm-circifier pull request #57
Opened 2023-06-29 10:58 UTC by CblPOK-git

Add mapping for curve type and base field type, rename wrong names that contained word "base", but really are "scalar"

2023-07-03 07:25 UTC, makxenov requested changes

2023-07-03 07:25 UTC, makxenov commented on llvm/include/llvm/IR/DerivedTypes.h
> +  GaloisFieldKind GetFieldFromCurve() const {
Let's rename this method to `GetBaseFieldKind`.

2023-07-03 07:25 UTC, makxenov commented on llvm/include/llvm/IR/DerivedTypes.h
> +    }
Please add `llvm_unreachable` for unknown kind

2023-07-03 07:25 UTC, makxenov commented on llvm/lib/IR/Instructions.cpp
>    // Curve can be multiplied only by corresponding base field type
Fix this comment as well

2023-07-03 11:15 UTC, makxenov approved these changes

2023-07-04 10:03 UTC, nkaskov approved these changes

2023-07-04 10:03 UTC, merged