Add `cdiv` instruction for curve by field division
NilFoundation/zkllvm-circifier pull request #79
Opened 2023-09-13 11:56 UTC by aleasims

2023-09-13 11:56 UTC, aleasims commented
Also this PR adds some C API functions, which are going to be used from Rust compiler.

2023-09-14 08:13 UTC, makxenov requested changes

2023-09-14 08:13 UTC, makxenov commented on llvm/include/llvm-c/Core.h
> +  LLVMCDiv           = 72,
Shouldn't the indices here be the same as in `Instruction.def` file?

2023-09-14 13:19 UTC, makxenov approved these changes

2023-09-19 19:15 UTC, aleasims commented
@makxenov CI succeeded in NilFoundation/zkllvm/pull/255. Ready to merge.

2023-09-22 15:54 UTC, makxenov approved these changes

2023-09-22 15:55 UTC, merged